# Generated by Django 4.0.4 on 2022-04-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderdetail_fk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='fk_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='order.orderdetail'),
        ),
    ]
