# Generated by Django 4.0.4 on 2022-04-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_fk_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fk_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category'),
        ),
    ]
